### ISSUE TITLE
"path.h" is missing

### ISSUE THREAD

**Issue by janisozaur** [X123M3-256/libRCT2#1]
```
In file included from small_scenery.c:5:0:
object.h:115:10: fatal error: path.h: No such file or directory
 #include "path.h"
          ^~~~~~~~
```

**Comment by janisozaur** [comment]
There are other files missing too, are they meant to be taken from openrct2?

**Comment by X123M3-256** [comment]
No, I must have forgotten to commit them to the repo. I see seven files missing, so I've added them. I'm able to clone the repo and build it now, so I think this particular issue is fixed.

**Comment by X123M3-256** [comment]
No, I must have forgotten to commit them to the repo. I see three files missing, I'll add them now.
